### ISSUE TITLE
缺少重要的信息

### ISSUE THREAD

**Issue by billypon** [secken/secken-ssh#3]
登录请求会自动发送到手机app上进行确认，但这个时候app上能看到这样的信息：

> Name: username
>    IP address: 0.0.0.0

缺少实际用户名和实际ip地址

**Comment by xiaochao** [comment]
这两个参数需要你通过API传给服务器的

**Comment by billypon** [comment]
@xiaochao 这个组件不是应该自动获取数据然后传递给API的吗？还需要自己二次开发添加参数？

**Comment by xiaochao** [comment]
恩，是需要自己加的
